name: my-workflow
run-name: ${{ github.actor }} is testing out Bun
on: [push]
jobs:
  my-job:
    name: Setting UP Bun
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
