name: Scrape lingbuzz
run-name: Scraping
on: [push]
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up bun
        uses: oven-sh/setup-bun@v1
      - name: Install depependencies
        run: bun install
      - name: Fetch the data
        run: bun run src/index.ts | jq .
      # - name: Commit and push if it changed
      #   run: |-
      #     git config user.name "Automated"
      #     git config user.email "actions@users.noreply.github.com"
      #     git add -A
      #     timestamp=$(date -u)
      #     git commit -m "Latest data: ${timestamp}" || exit 0
      #     git push
