name: Scrape lingbuzz
run-name: Scraping

on:
  schedule:
    - cron:  '1 0 * * *'
  
jobs:
  scraper:
    runs-on: ubuntu-latest
    permissions: # Job-level permissions configuration starts here
      contents: write # 'write' access to repository contents
      pull-requests: write # 'write' access to pull requests
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up bun
        uses: oven-sh/setup-bun@v1
      - name: Install depependencies
        run: bun install
      - name: Fetch the data
        run: bun run src/index.ts
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
